# Generated by Django 4.2.11 on 2024-05-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
