# Generated by Django 4.2.13 on 2024-05-23 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comandes', '0003_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='comandes.cliente'),
            preserve_default=False,
        ),
    ]
